import localFont from "next/font/local";
import "@/app/_styles/globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { CartProvider } from "./_components/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
//       >
//         <header>
//           <Header />
//         </header>
//         <div className="flex-1 px-8 py-12 grid">
//           <main>{children}
//           </main>
//         </div>
//         {/* <footer className="flex-shrink-0">
//           <Footer />
//         </footer> */}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-white">
        <header className="w-full py-2 fixed top-0 left-0 bg-white z-50">
          <Header />
        </header>

        <main className="flex-grow w-full pt-[60px]">
          <CartProvider>{children}</CartProvider>
        </main>

        <footer className="w-full">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
